apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-addresspool-tf-cluster
  namespace: metallb-system
spec:
  addresses:
    # Availabel IP pool- 10.0.0.7-10.0.0.9
    - 10.0.0.8

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - ip-addresspool-tf-cluster

