---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-claim
  labels:
    app: prometheus
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graf-claim
  labels:
    app: grafana
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi