---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-claim
  namespace: monitoring
  labels:
    app: prometheus
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi